services:
  api_agent:
    build:
      context: ./api_agent
      dockerfile: Dockerfile
    volumes:
      - ./api_agent:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  api_data:
    build:
      context: ./api_data
      dockerfile: Dockerfile
    volumes:
      - ./api_data:/app
    ports:
      - "8001:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  streamlit_frontend:
    build:
      context: ./streamlit_frontend
      dockerfile: Dockerfile
    volumes:
      - ./streamlit_frontend:/app
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0