project_id      = "dataproject3-458310"
region          = "europe-west1"
zone            = "europe-west1-b"
topic_vuelos    = "vuelos"
topic_hoteles   = "hoteles"
bq_dataset      = "app_viajes"
table_vuelos   = "vuelos"
table_hoteles   = "hoteles"